# Generated by Django 2.2.5 on 2019-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_formulario', models.CharField(max_length=8)),
                ('nombre_responsable', models.CharField(max_length=15)),
                ('bibloteca', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_informe', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
    ]
