# Generated by Django 2.2.5 on 2019-10-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id_formulario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
    ]
