# Generated by Django 2.2.5 on 2019-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_auto_20191014_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.IntegerField()),
                ('cd', models.IntegerField()),
                ('libros', models.IntegerField()),
                ('ssue', models.IntegerField()),
                ('nombre_concepto', models.CharField(max_length=30)),
                ('id_formulario', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_usuario',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
