# Generated by Django 2.2.5 on 2019-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0003_auto_20191015_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='nombre_concepto',
            field=models.CharField(max_length=50),
        ),
    ]
