# Generated by Django 2.2.5 on 2019-10-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0004_auto_20191015_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='id_formulario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
